version: "3.8"

services:
  ###
  # S3-API: http://127.0.0.1:9000
  # Console: http://127.0.0.1:9001
  s3_image:
    hostname: net-forge-s3
    container_name: net-forge-s3
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ROOT_USER: minioUser
      MINIO_ROOT_PASSWORD: minioPassword
    command: server --console-address ":9001" /data

volumes:
  redis-storage:
    driver: local
  minio-storage: {}
