[[ build.env ]]
    name = 'BP_DOTNET_PROJECT_PATH'
    value = 'demo/Saritasa.NetForge.Demo.Net7'

[[ build.env ]]
    name = 'BP_DOTNET_PUBLISH_FLAGS'
    value = '--self-contained=true --framework=net7.0'

[[ build.buildpacks ]]
    id = "paketo-buildpacks/dotnet-core"
    version = "0.42.1"
