version: "3.8"

services:
  ###
  # Postgres demo database
  postgres:
    hostname: netforge-db
    container_name: netforge-db
    image: postgres:13
    ports:
      - "5432:5432" # database
    environment:
      - POSTGRES_DB=netforge
      - POSTGRES_USER=netforge
      - POSTGRES_PASSWORD=1
    volumes:
      - .data/pgdata:/var/lib/postgresql/data

  ###    
  # S3-API: http://127.0.0.1:9000
  # Console: http://127.0.0.1:9001
  s3_image:
    hostname: net-forge-s3
    container_name: net-forge-s3
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ROOT_USER: minioUser
      MINIO_ROOT_PASSWORD: minioPassword
    command: server --console-address ":9001" /data

volumes:
  minio-storage: {}
